var measurementsModel = {
        personal:{
            'family-name' : ko.observable(''),
            'given-name' : ko.observable(''),
            'birth-date' : ko.observable(null),
            'sex': ko.observable('male'),
            'email': ko.observable('')
        },
        measurements:{
            unit: ko.observable('cm'),
            head_and_neck:{
                head_girth: metrics['a-1'].value,
                mid_neck_girth: metrics['a-1'].value,
                neck_base_girth: metrics['a-1'].value,
                head_and_neck_length: metrics['a-1'].value
            },
            torso:{
                center_front_waist_length: metrics['a-1'].value,
                center_back_waist_length: metrics['a-1'].value,
                shoulder_length: metrics['a-1'].value,
                side_waist_length: metrics['a-1'].value,
                trunk_length: metrics['a-1'].value,
                shoulder_girth: metrics['a-1'].value,
                upper_chest_girth: metrics['a-1'].value,
                bust_girth: metrics['a-1'].value,
                under_bust_girth: metrics['a-1'].value,
                waist_girth: metrics['a-1'].value,
                high_hip_girth: metrics['a-1'].value,
                hip_girth: metrics['a-1'].value,
                upper_front_chest_width: metrics['a-1'].value,
                front_chest_width: metrics['a-1'].value,
                across_front_shoulder_width: metrics['a-1'].value,
                across_back_shoulder_width: metrics['a-1'].value,
                upper_back_width: metrics['a-1'].value,
                back_width: metrics['a-1'].value,
                bustpoint_to_bustpoint: metrics['a-1'].value,
                halter_bustpoint_to_bustpoint: metrics['a-1'].value,
                neck_to_bustpoint: metrics['a-1'].value,
                crotch_length: metrics['a-1'].value,
                rise_height: metrics['a-1'].value,
                shoulder_drop: metrics['a-1'].value,
                shoulder_slope_degrees: metrics['a-1'].value,
                front_shoulder_slope_length: metrics['a-1'].value,
                back_shoulder_slope_length: metrics['a-1'].value,
                front_shoulder_to_waist_length: metrics['a-1'].value,
                back_shoulder_to_waist_length: metrics['a-1'].value,
                front_neck_arc: metrics['a-1'].value,
                back_neck_arc: metrics['a-1'].value,
                front_upper_chest_arc: metrics['a-1'].value,
                back_upper_chest_arc: metrics['a-1'].value,
                front_waist_arc: metrics['a-1'].value,
                back_waist_arc: metrics['a-1'].value,
                front_upper_hip_arc: metrics['a-1'].value,
                back_upper_hip_arc: metrics['a-1'].value,
                front_hip_arc: metrics['a-1'].value,
                back_hip_arc: metrics['a-1'].value,
                chest_slope: metrics['a-1'].value,
                back_slope: metrics['a-1'].value,
                front_waist_slope: metrics['a-1'].value,
                back_waist_slope: metrics['a-1'].value,
                front_neck_to_upper_chest_height: metrics['a-1'].value,
                front_neck_to_bust_height: metrics['a-1'].value,
                front_waist_to_upper_chest: metrics['a-1'].value,
                front_waist_to_lower_breast: metrics['a-1'].value,
                back_waist_to_upper_chest: metrics['a-1'].value,
                strap_length: metrics['a-1'].value
            },
            arm:{
                armscye_girth: metrics['a-1'].value,
                elbow_girth: metrics['a-1'].value,
                upper_arm_girth: metrics['a-1'].value,
                wrist_girth: metrics['a-1'].value,
                scye_depth: metrics['a-1'].value,
                shoulder_and_arm_length: metrics['a-1'].value,
                underarm_length: metrics['a-1'].value,
                cervicale_to_wrist_length: metrics['a-1'].value,
                shoulder_to_elbow_length: metrics['a-1'].value,
                arm_length: metrics['a-1'].value
            }, 
            hand:{
                hand_width: metrics['a-1'].value,
                hand_length: metrics['a-1'].value,
                hand_girth: metrics['a-1'].value
            }, 
            leg:{
                thigh_girth: metrics['a-1'].value,
                mid_thigh_girth: metrics['a-1'].value,
                knee_girth: metrics['a-1'].value,
                calf_girth: metrics['a-1'].value,
                ankle_girth: metrics['a-1'].value,
                knee_height: metrics['a-1'].value,
                ankle_height: metrics['a-1'].value
            }, 
            foot:{
                foot_width: metrics['a-1'].value,
                foot_length: metrics['a-1'].value
            }, 
            heights:{
                height: metrics['a-1'].value,
                cervicale_height: metrics['a-1'].value,
                cervicale_to_knee_height: metrics['a-1'].value,
                waist_height: metrics['a-1'].value,
                high_hip_height: metrics['a-1'].value,
                hip_height: metrics['a-1'].value,
                waist_to_hip_height: metrics['a-1'].value,
                waist_to_knee_height: metrics['a-1'].value,
                crotch_height: metrics['a-1'].value
            },
            extended:{
                size: metrics['a-1'].value,
                height_front_neck_base_point: metrics['a-1'].value,
                height_base_neck_side_point: metrics['a-1'].value,
                height_shoulder_point: metrics['a-1'].value,
                height_nipple_point: metrics['a-1'].value,
                height_back_angle_axilla: metrics['a-1'].value,
                height_scapular_point: metrics['a-1'].value,
                height_under_buttock_folds: metrics['a-1'].value,
                hips_excluding_protruding_abdomen: metrics['a-1'].value,
                girth_foot_instep: metrics['a-1'].value,
                side_waist_to_floor: metrics['a-1'].value,
                front_waist_to_floor: metrics['a-1'].value,
                arc_through_groin_area: metrics['a-1'].value,
                waist_to_plane_seat: metrics['a-1'].value,
                neck_to_radial_point: metrics['a-1'].value,
                neck_to_third_finger: metrics['a-1'].value,
                neck_to_first_line_chest_circumference: metrics['a-1'].value,
                front_waist_length: metrics['a-1'].value,
                arc_through_shoulder_joint: metrics['a-1'].value,
                neck_to_back_line_chest_circumference: metrics['a-1'].value,
                waist_to_neck_side: metrics['a-1'].value,
                arc_length_upper_body: metrics['a-1'].value,
                chest_width: metrics['a-1'].value,
                anteroposterior_diameter_hands: metrics['a-1'].value,
                height_clavicular_point: metrics['a-1'].value,
                height_armhole_slash: metrics['a-1'].value,
                slash_shoulder_height: metrics['a-1'].value,
                half_girth_neck: metrics['a-1'].value,
                half_girth_neck_for_shirts: metrics['a-1'].value,
                half_girth_chest_first: metrics['a-1'].value,
                half_girth_chest_second: metrics['a-1'].value,
                half_girth_chest_third: metrics['a-1'].value,
                half_girth_waist: metrics['a-1'].value,
                half_girth_hips_considering_protruding_abdomen: metrics['a-1'].value,
                half_girth_hips_excluding_protruding_abdomen: metrics['a-1'].value,
                girth_knee_flexed_feet: metrics['a-1'].value,
                neck_transverse_diameter: metrics['a-1'].value,
                front_slash_shoulder_height: metrics['a-1'].value,
                neck_to_front_waist_line: metrics['a-1'].value,
                hand_vertical_diameter: metrics['a-1'].value,
                neck_to_knee_point: metrics['a-1'].value,
                waist_to_knee: metrics['a-1'].value,
                shoulder_height: metrics['a-1'].value,
                head_height: metrics['a-1'].value,
                body_position: metrics['a-1'].value,
                arc_behind_shoulder_girdle: metrics['a-1'].value,
                neck_to_neck_base: metrics['a-1'].value,
                depth_waist_first: metrics['a-1'].value,
                depth_waist_second: metrics['a-1'].value
            }
        }
    };